<?php
/**
 * @file
 * Code for the Spanien default content feature.
 */

include_once('spanien_default_content.features.inc');

/**
 * Implements hook_menu_block_blocks().
 */
function spanien_default_content_menu_block_blocks() {
  // The array key is the block delta used by menu block.
  return array(
    'spanien_default_content-1' => array(
      'menu_name'   => MENU_TREE__CURRENT_PAGE_MENU,
      'parent_mlid' => 0,
      'title_link'  => 1,
      'admin_title' => 'Menu sidebar',
      'level'       => 2,
      'follow'      => active,
      'depth'       => 0,
      'expanded'    => 0,
      'sort'        => 0,
    ),
  );
}
