<?php

/**
 * Implements hook_image_styles_alter
 */
function badspa_admin_image_styles_alter(&$styles) {

  // Update the featured content image width.
  if (isset($styles['panorama_image'])) {
    $styles['panorama_image']['effects'][5]['data']['width'] = 980;
    $styles['panorama_image']['effects'][5]['data']['height'] = 248;
  }

  if (isset($styles['spotbox_image'])) {
    $styles['spotbox_external_link_image']['effects'][4]['data']['width'] = 375;
    $styles['spotbox_external_link_image']['effects'][4]['data']['height'] = 155;
  }
}